public class createproject {
// Method to add two numbers
    public Integer addNumbers(Integer num1, Integer num2) {
        Integer sum = num1 + num2;
        return sum;
    }

    // Method to greet a user
    public String greetUser(String name) {
        return 'Hello, ' + name + '! Welcome to almost new Salesforce Apex!';
    }
    public String greetUser2(String name) {
        return 'Hello, ' + name + '! Welcome to almost new Salesforce Apex!';
    }
    public String greetUser3(String name) {
        return 'Hello, ' + name + '! Welcome to almost new Salesforce Apex!';
    }
    public String greetUser4(String name) {
        return 'Hello, ' + name + '! Welcome to almost new Salesforce Apex!';
    }
}